#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
	/config/keys

# copy default scripts from install
if [[ ! -e /config/scripts ]]; then
	cp -R /defaults/scripts /config/
fi

# generate ssl certificate
if [[ -z ${TEST_RUN+x} ]]; then
	if [[ ! -e /config/keys/server_cert.pem ]]; then
		[[ -e /config/keys/RSA2048.pem ]] && rm /config/keys/RSA2048.pem
			openssl dhparam -out /config/keys/RSA2048.pem -5 2048
			openssl req -x509 -nodes -days 3650 \
			-newkey rsa:2048 -keyout /config/keys/server_cert.pem  -out /config/keys/server_cert.pem \
			-subj "/CN=domoticz"
			cat /config/keys/RSA2048.pem >> /config/keys/server_cert.pem
	fi
fi

# set permissions
lsiown -R abc:abc \
	/config \
	/tmp \
	/usr/share/domoticz
