#!/usr/bin/with-contenv bash

IFS=" " read -r -a RUN_ARRAY <<< "$WEBROOT"

# set capabilities for domoticz binary
setcap cap_net_raw=+eip /var/lib/domoticz/domoticz

exec \
	s6-setuidgid abc /var/lib/domoticz/domoticz \
		-sslwww 1443 \
		-sslcert /config/keys/server_cert.pem \
		-userdata /config/ \
		-dbase /config/domoticz.db \
		-webroot "${RUN_ARRAY[@]}"
