#!/usr/bin/with-contenv bash

# copy default scripts from install
[[ ! -e /config/scripts ]] && \
	cp -R /opt/domoticz/scripts /config/

# copy default ssl certificate
[[ ! -e /config/server_cert.pem ]] && \
	cp /opt/domoticz/server_cert.pem /config/server_cert.pem

# set permissions for /config
chown -R abc:abc \
	/config
chmod -R 764 \
	/config
